'use client';
import {useState} from 'react';
import {format,parseISO,startOfMonth,startOfWeek,endOfMonth,endOfWeek} from 'date-fns';
import {Check,Save} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {today,dateLabel} from '@/lib/dates';
import {rowTitle,type DataRow} from '@/lib/entities';
import {errorMessage} from '@/lib/validation';
import {supabase} from '@/lib/supabase';
import {useApp} from './provider';
import {PageHeading,Empty,Collection,Badge} from './shared';
const statuses=['Presente','Falta','Retraso','Xustificada'];
export function Attendance(){const{data}=useApp();const[date,setDate]=useState(today()),[group,setGroup]=useState(''),[mode,setMode]=useState('Rexistrar'),[student,setStudent]=useState('');const pupils=data.students.filter(s=>!group||s.group_id===group);const records=data.attendance.filter(r=>pupils.some(s=>s.id===r.student_id)&&(!student||r.student_id===student));const ref=parseISO(date);const range=mode==='Semana'?[format(startOfWeek(ref,{weekStartsOn:1}),'yyyy-MM-dd'),format(endOfWeek(ref,{weekStartsOn:1}),'yyyy-MM-dd')]:mode==='Mes'?[format(startOfMonth(ref),'yyyy-MM-dd'),format(endOfMonth(ref),'yyyy-MM-dd')]:mode==='Por alumno/a'||mode==='Por grupo'?['0000-01-01','9999-12-31']:[date,date];const filtered=records.filter(r=>String(r.date)>=range[0]&&String(r.date)<=range[1]);
 return <><PageHeading eyebrow="UN XESTO, TODO O GRUPO" title="Faltas de asistencia" description="Pasa lista, rexistra ausencias e consulta o historial."/><div className="tabs">{['Rexistrar','Hoxe','Semana','Mes','Por alumno/a','Por grupo'].map(v=><button key={v} className={mode===v?'active':''} onClick={()=>{setMode(v);if(v==='Hoxe')setDate(today());}}>{v}</button>)}</div><div className="attendance-controls panel"><label>Data<input type="date" value={date} required onChange={e=>{if(e.target.value)setDate(e.target.value);}}/></label><label>Grupo<select value={group} onChange={e=>setGroup(e.target.value)}><option value="">Selecciona un grupo</option>{data.groups.filter(g=>!g.archived).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label>{mode==='Por alumno/a'&&<label>Alumno/a<select value={student} onChange={e=>setStudent(e.target.value)}><option value="">Todo o alumnado</option>{pupils.map(s=><option value={s.id} key={s.id}>{rowTitle('students',s)}</option>)}</select></label>}</div>{mode==='Rexistrar'?group?<AttendanceRoll key={`${date}-${group}`} date={date} students={pupils}/>:<Empty title="Comeza por seleccionar un grupo" description="Verás o alumnado e poderás pasar lista cun só toque."/>:<><div className="mini-stats">{[['Faltas totais',filtered.filter(r=>['Falta','Xustificada'].includes(String(r.status))).length],['Xustificadas',filtered.filter(r=>r.status==='Xustificada').length],['Non xustificadas',filtered.filter(r=>r.status==='Falta').length],['Retrasos',filtered.filter(r=>r.status==='Retraso').length]].map(([s,n])=><div key={s}><strong>{n}</strong><span>{s}</span></div>)}</div><Collection table="attendance" rows={filtered}/></>}</>;
}
function AttendanceRoll({date,students}:{date:string;students:DataRow[]}){const{data,user,reload,notice}=useApp();const[draft,setDraft]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false);const existing=data.attendance.filter(r=>r.date===date);const status=(id:string)=>draft[id]??existing.find(r=>r.student_id===id)?.status??'';
 const save=async()=>{if(!Object.keys(draft).length)return;setBusy(true);try{const rows=Object.entries(draft).map(([student_id,status])=>({user_id:user!.id,student_id,date,status}));const{error}=await supabase().from('attendance').upsert(rows,{onConflict:'user_id,student_id,date'});if(error)throw error;await reload();setDraft({});notice('Asistencia gardada correctamente');}catch(e){notice(errorMessage(e),true);}finally{setBusy(false);}};
 return <section className="panel"><div className="panel-heading"><div><h2>{dateLabel(date,"EEEE, d 'de' MMMM")}</h2><p>{students.length} alumnos/as · {students.filter(s=>status(s.id)).length} rexistrados</p></div><Button variant="outline" disabled={busy||!students.length} onClick={()=>setDraft(Object.fromEntries(students.map(s=>[s.id,'Presente'])))}><Check size={17}/>Todos presentes</Button></div>{students.length?<div className="attendance-list">{students.map(s=><div className="attendance-row" key={s.id}><div className="attendance-student"><div className="avatar">{String(s.first_name).slice(0,1)}</div><strong>{rowTitle('students',s)}</strong>{!status(s.id)&&<Badge tone="gray">Sen rexistrar</Badge>}</div><div className="status-options" role="group" aria-label={`Asistencia de ${rowTitle('students',s)}`}>{statuses.map((value,i)=><button disabled={busy} key={value} aria-pressed={status(s.id)===value} className={`status-option status-${i} ${status(s.id)===value?'selected':''}`} onClick={()=>setDraft({...draft,[s.id]:value})}>{value}</button>)}</div></div>)}</div>:<Empty title="Este grupo aínda non ten alumnado" description="Engade alumnado na súa sección antes de pasar lista."/>}<div className="attendance-save"><span>{Object.keys(draft).length?`${Object.keys(draft).length} cambios pendentes`:'Sen cambios pendentes'}</span><Button className="primary" disabled={busy||!Object.keys(draft).length} onClick={()=>void save()}><Save size={17}/>{busy?'Gardando…':'Gardar asistencia'}</Button></div></section>;
}

